hello: world
example: fill me in with {0} or {1} parameters
# COMPONENT BLOCKS
component:
  apiError:
    # title of API error:
    title: Gomenasorry!
    # this line should apologize, ask to use the following link for twitter
    textBeforeTwitter: 'There was an error retrieving content, please check twitter ' 
    # twitterHandle: '@holodex' <-- this is unused
    # and this line should chain smoothly into About page link.
    textAfterTwitter: ' or report an error through the' 
    aboutPage: 'About page'
  channelInfo:
    videoCount: '{0} Videos'
    clipCount: '{0} Clips'
    subscriberCount: '{0} Subscribers'
    subscriberNA: 'Subscriber count unavailable'
  channelSocials:
    addToFavorites: 'Add to Favorites'
    removeFromFavorites: 'Remove from Favorites'
  mainNav: # main navigation menu
    home: Home
    favorites: Favorites
    channels: channels
    about: About
    settings: Settings
  videoCard:
    clips: '{0} Clips'
    watching: '{0} Watching'
    liveNow: 'Live Now'
  videoDescription:
    description: 'Description' # header text of the description section. User clicks this to open description.

# VIEWS
views:
  channels: # tells you if a channel is a clipper subber or vtuber
    channelType:  
      subber: subber
      vtuber: vtuber
    sortOptions: # enumerates the dropdown list for picking how you want to sort the list of channels
      subscribers: Subscribers
      group: Group
      recentUpload: Recent Upload
      videoCount: Video Count
      clipCount: Clip Count
    tabs: # each tab shows the channels in the HoloDex DB corresponding to that type
      Vtuber: Vtuber
      Subber: Subber
      Favorites: Favorites
  home:
    liveOrUpcomingHeading: Live / Upcoming
    recentVideosHeading: Recent Videos
    recentVideoToggles:
      all: All
      official: Official
      subber: Clips
  notFound:
    title: Content not found
    back: Return Home
  search:
    sort:
      newest: Newest
      oldest: Oldest
    type:
      all: All
      official: Official
      clip: Clip
  settings:
    title: Settings
    darkModeLabel: Dark Mode
    darkModeMsg: Changes the theme between light mode and dark mode
    redirectModeLabel: Redirect Mode 
    redirectModeMsg: Clicking on a video takes you straight to the youtube video
    useEnglishNameLabel: Use English Name
    useEnglishNameMsg: Uses English localized names for VTuber channels
    hideVideoThumbnailsLabel: Hide Video Thumbnails
    hideVideoThumbnailsMsg: Hide video thumbnails, helps speed up loading time and less scrolling on mobile
    resetAllSettings: Reset All Settings/Data
  